ID='Identifier'
NAME='Company Name'
COUNTRY='Country of Headquarters'
IPO='IPO Date'
INDUSTRY='Industry name'
BALANCE_SHEET_DATE='Balance Sheet Period End Date'
ASSETS='Total Assets'
EQUITY="Total Shareholders' Equity"
ACC_STANDARD='Balance Sheet Accounting Standard'
PRICE='Price Close'
COMMON_SHARES_OUTSTANDING="Common Shares - Outstanding"
NET_INCOME_BEFORE_EXTRAORDINARY="Net Income Before Extraordinary Items"
NET_CASHFLOW_FROM_OPERATING_ACTIVITIES="Net Cash Flow from Operating Activities"
COMMON_EQUITY="Common Equity"
BOOK_VALUE_PER_SHARE="Book Value Per Share, Total Equity"
#TOTAL_RETURN_YTD="YTD Total Return"
MATCH = "MATCH"
YEAR = "Year"

VARIABLES = [
    ASSETS,
    EQUITY,
    ACC_STANDARD,
    PRICE,
    COMMON_SHARES_OUTSTANDING,
    NET_INCOME_BEFORE_EXTRAORDINARY,
    NET_CASHFLOW_FROM_OPERATING_ACTIVITIES,
    COMMON_EQUITY,
    BOOK_VALUE_PER_SHARE,
#    TOTAL_RETURN_YTD
]

HEADERS = [
    ID,
    YEAR,
    NAME,
    MATCH,
    COUNTRY,
    IPO,
    INDUSTRY,
    BALANCE_SHEET_DATE,
    ACC_STANDARD,
    ASSETS,
    EQUITY,
    PRICE,
    COMMON_SHARES_OUTSTANDING,
    NET_INCOME_BEFORE_EXTRAORDINARY,
    NET_CASHFLOW_FROM_OPERATING_ACTIVITIES,
    COMMON_EQUITY,
    BOOK_VALUE_PER_SHARE,
 #   TOTAL_RETURN_YTD
    ]